demo/config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :category

  resources :newmessages do
    resources :comments , :controller => 'comments'
  end

  root :to => "newmessages#index"

end

demo/app/models/category.rb
class Category < ActiveRecord::Base
  validates_presence_of :name
  has_many :newmessages, :dependent => :destroy

end

demo/app/models/comment.rb
class Comment < ActiveRecord::Base
  validates_presence_of :comment
  belongs_to :newmessage
  belongs_to :user
end

demo/app/models/newmessage.rb
class Newmessage < ActiveRecord::Base
  validates_presence_of :topic, :content, :category_id
  has_many :comments, :dependent => :destroy
  belongs_to :user
  belongs_to :category
  delegate :name, :to => :category, :prefix => true, :allow_nil => true

end

demo/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         has_many :newmessages
         has_many :comments
end

demo/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) << :first_name
      devise_parameter_sanitizer.for(:sign_up) << :last_name

      devise_parameter_sanitizer.for(:account_update) << :first_name
      devise_parameter_sanitizer.for(:account_update) << :last_name

    end

  def set_message
    @newmessage = Newmessage.find( params[:newmessage_id] )
  end

end

demo/app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  # before_action :set_comment
  before_action :authenticate_user!, :except => [:index, :show]
  before_action :set_message
  def update
    # /newmessage/123/comments/456 == newmessage_comment_path(123,456)
    # Parameter = { :xxx => yyy, :jfisojfio => ffdhuhfe,
    # :newmessage_id => 123, :id => 456}
    # @comment = Comment.find(params[:id])
    @comment = @newmessage.comments.find(params[:id])
      if @comment.update(comment_params)
      redirect_to newmessage_path(@newmessage)
      flash[:notice] = "修改成功"
    else
      render "newmessages/show"
    end

  end

  def create
    @comment = Comment.new( comment_params )
    @comment.newmessage = @newmessage
    @comment.user = current_user
    if @comment.save
      redirect_to newmessage_path(@newmessage)
      flash[:notice] = "新增成功"
    else
      render "newmessages/show"
    end
  end

  def destroy
      @comment = @newmessage.comments.find(params[:id])
      @comment.destroy
      flash[:alert] = "刪除成功"
      redirect_to newmessage_path(@newmessage)
  end

  protected

  def comment_params
    params.require(:comment).permit(:comment, :newmessage_id, :user_id)
  end

# def set_comment
  # @comment = @newmessage.comments
# end

end

demo/app/controllers/newmessages_controller.rb
class NewmessagesController < ApplicationController

  before_action :authenticate_user!, :except => [:index]

  def index

    if params[:cid]
      @category = Category.find( params[:cid] )
      @newmessages = @category.newmessages
    else
      @newmessages = Newmessage.all
    end

    @newmessages = @newmessages.page(params[:page]).per(10)

    #Parameter = {hfsj jfidshi fd , :category => "xxx"}
    # if params[:category]
    # @category = Category.find(params[:id])
     # @category.newmessages = @newmessage
     # @newmessage.category = @category
    # @newmessages = Newmessage.where().page(params[:page]).per(10)

    # prepare_variable_for_index_template


  end

  def show
    @newmessage = Newmessage.find(params[:id])
    @newmessage.user= current_user
    # @newmessage.view_count += 1



    if params[:cid]
    @comment = Comment.find(params[:cid])
    else
    @comment = Comment.new
    end
  end

  def new
    @newmessage = Newmessage.new
  end

  def create
    @newmessage = Newmessage.new( newmessage_params )
    @newmessage.user = current_user
    if @newmessage.save
      flash[:notice] = "新增成功"
        redirect_to newmessages_url
    else
    render :action => :new   # new.html..erb
        # 當輸入沒填滿則顯示警告視窗
    end

  end

  def edit
    @newmessage = Newmessage.find(params[:id])

  end

  def update

      @newmessage = Newmessage.find(params[:id])
      if@newmessage.update(newmessage_params)

      flash[:notice] = "編輯成功"

      redirect_to newmessage_url
       else
      render :action => :edit
     end
  end


   def destroy
       @newmessage = Newmessage.find(params[:id])

       @newmessage.destroy
      # @comments.newmessage = @newmessage

       flash[:alert] = "刪除成功"

       redirect_to newmessages_url(:page => params[:page])
    end


       private


  # def prepare_variable_for_index_template

    # if params[:keyword]
        # @newmessages = Newmessage.where(["name like ?", "%#{params[:keyword]}%" ] )
    # else
        # @newmessages = Newmessage.all
  # end

    # if params[:category => 1]
        # sort_by = (params[:category] == 1 )? 'name' : 'id'
        # @newmessages = @newmessages.order(sort_by)
    # end

      # @newmessages =@newmessages.page(params[:page]).per(5)


   def newmessage_params
    params.require(:newmessage).permit(:topic, :content, :category_id, :user_id)
   end

end

demo/app/helpers/application_helper.rb
module ApplicationHelper
end

demo/app/helpers/comments_helper.rb
module CommentsHelper
end

demo/app/helpers/newmessages_helper.rb
module NewmessagesHelper
end

demo/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @page_title || "Rails Exercise"%></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <div class="row">
    <div class="col-md-12">
     <% if flash[:notice].present? %>
        <div class="alert alert-success" role="alert"><%= flash[:notice] %>
        </div>
        <% end %>

      <% if flash[:alert].present? %>
        <div class="alert alert-danger" role="alert"><%= flash[:alert] %></div>
        <% end %>


      <% if current_user %>

       Hi，<%= current_user.last_name || current_user.email  %>
          <%= link_to '登出', destroy_user_session_path, :class => "btn btn-primary", :method => :delete %>
          <%= link_to '修改密碼', edit_registration_path(:user),:class => "btn btn-primary" %>
      <% else %>
          <%= link_to '註冊', new_registration_path(:user) %>
          <%= link_to '登入', new_session_path(:user) %>
      <% end %>



        <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

      <%= yield %>
    </div>
  </div>
</div>
</body>
</html>

demo/app/views/newmessages/_form.html.erb
<% if @newmessage.errors.any? %>
      <ul>
        <% @newmessage.errors.full_messages.each do |msg| %>

        <li><%= msg %></li>

        <% end %>
      </ul>
<% end %>
<table>

<div class="form-group">
    <%= f.label :category_id, "Category" %>

    <% Category.all.each do |c| %>
    <%= f.radio_button :category_id, c.id %> <%= c.name %>
      <% end %>
</div>
<hr>
<div class="form-group">
    <%= f.label :topic, "Topic" %>
    <%= f.text_field :topic, :required => true, :class => "form-control" %>
</div>
<hr>
<div class="form-group">
    <%= f.label :content, "Content" %>
    <%= f.text_area :content, :class => "form-control" %>
</div>
</table>

demo/app/views/newmessages/edit.html.erb
<%= form_for @newmessage, :url => newmessage_path(@newmessage),:method =>:patch do |f| %>

<%= render :partial => "form", :locals => {:f => f} %>

<br><%= f.submit "更新修改", :class => "btn btn-primary" %>

<%= link_to "返回", newmessages_path, :class => "btn btn-default" %>
<% end %>

demo/app/views/newmessages/index.html.erb
<h1 style="color: red">Breaking News</h1> <%= Time.now%>

<div class="container" style="background: grey">
  <h1 style="color: brown", align="center"> 佈告欄 </h1>
</div>

<%= form_tag newmessages_path, :method => :get do %>
  <%= text_field_tag "keyword" %>
  <%= submit_tag "Search" %>
<% end %>

文章分類：
<% Category.all.each do |c| %>
  <%= link_to c.name, newmessages_path( :cid => c ) %>
<% end %>

<table>
  <caption style="background: red"> 即時訊息 </caption>
  <thead>
    <tr>
      <th>文章標題</th>
      <th>分類</th>
      <th>作者</th>
      <th>建立時間</th>
      <th>內容</th>
      <th>回覆</th>
      <th>詳細內容</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  <% @newmessages.each do |n| %>
    <tr style="background: grey">
      <td><%= n.topic %></td>
      <td><%= n.category_name %></td>
      <td><%= n.user.try(:last_name) %></td>
      <td><%= n.created_at %></td>
      <td><%= n.content %></td>
      <td><%= n.comments.size %></td>
      <td>
          <%= link_to "進入", newmessage_path(n),:class => "btn btn-primary" %>
      </td>
      <td>
          <%= link_to "編輯", edit_newmessage_path(n),:class => "btn btn-primary" %>
      </td>
      <td>
          <%= link_to "刪除", newmessage_path(n), :method => :delete,  :data => { :confirm => "Are You Sure?" }, :class => "btn btn-danger" %>
      </td>
    </tr>
  </tbody>
  <% end %>
</table>


<%= paginate @newmessages %>





<hr>

<p><%= link_to '發表文章', new_newmessage_path %></p>

demo/app/views/newmessages/new.html.erb
<%= form_for @newmessage, :url => newmessages_path do |f| %>

    <%= render :partial => "form", :locals => {:f => f} %>

    <%= f.submit "Create", :class => "btn btn-success" %>

<% end %>

demo/app/views/newmessages/show.html.erb
<h2><%= "文章標題：" + @newmessage.topic%></h2>
<%= "發布時間 :" %>
<%=  @newmessage.created_at %>


<hr>

<%= "類別: " + @newmessage.category.name %>
<hr>
 <%= "發表內容： "%>

    <%= simple_format(@newmessage.content)%>


<% if false %>

<% end %>


<table style="background: grey">
<% @newmessage.comments.each do |c| %>
  <caption> </caption>
  <thead>
    <tr>
      <th>
        <%= link_to "編輯",
        newmessage_path(cid: c.id), :class => "btn btn-primary"%>
      </th>
      <th>
        <%= link_to "刪除", newmessage_comment_path(@newmessage,c), :method => :delete, :data => { :confirm => "Are You Sure?" }, :class => "btn btn-danger" %>
      </th>
      <th>發表人：</th>
      <th>內容： </th>
      <th>發表時間：</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td></td>
      <td></td>
      <td> <%= c.user.email %> </td>
      <td style="color: blue"> <%= c.comment %> </td>
      <td>
          <%=c.created_at.to_s(:short) %>
      </td>
    </tr>
  </tbody>
  <% end%>
</table>


<%= form_for [@newmessage, @comment] do |f| %>
<% if @comment.errors %>
  <ul>
  <% @comment.errors.full_messages.each do |e| %>
    <li><%= e %></li>
  <% end %>
  </ul>
<% end %>

  <div class="form-group">
  <%= f.label :comment, "留言" %>
    <%= f.text_area :comment, :required => true, :class => "form-control" %>
  </div>

  <%= f.submit "新增留言", :class => "btn btn-primary" %>
<% end %>

  <p><%= link_to 'Back to index', newmessages_path %></p>